#
# plugins.zsh
# generated by zpacman, do not edit
#

plugins=(
	adb
	archlinux
	autojump
	colored-man-pages
	command-not-found
	copypath copyfile
	cp
	docker
	extract
	git
	github
	gradle
	history-substring-search
	kate
	python
	rand-quote
	safe-paste
	ssh
	sudo
	tmux
	ufw
	vscode
	web-search
	z
	zsh-autosuggestions	# https://github.com/zsh-users/zsh-autosuggestions
	zsh-random-quotes	# https://github.com/vkolagotla/zsh-random-quotes
	zsh-syntax-highlighting	# https://github.com/zsh-users/zsh-syntax-highlighting
	zsh-you-should-use	# https://github.com/MichaelAquilina/zsh-you-should-use
)
