#
# plugins.zsh
# generated by zpacman, do not edit
#

plugins=(
	adb
	archlinux
	autojump
	colored-man-pages
	command-not-found
	copypath copyfile
	cp
	docker
	emoji
	emoji-clock
	extract
	eza
	fzf
	gh
	git
	git-lfs
	github
	gitignore
	gradle
	history-substring-search
	kate
	python
	rand-quote
	safe-paste
	ssh
	sudo
	tmux
	ufw
	vscode
	web-search
	z
	zsh-autosuggestions	# https://github.com/zsh-users/zsh-autosuggestions
	zsh-random-quotes	# https://github.com/vkolagotla/zsh-random-quotes
	zsh-syntax-highlighting	# https://github.com/zsh-users/zsh-syntax-highlighting
	zsh-wakatime	# https://github.com/wbingli/zsh-wakatime
	zsh-you-should-use	# https://github.com/MichaelAquilina/zsh-you-should-use
	zsh-zpacman	# https://github.com/Yttehs-HDX/zsh-zpacman
)
